library(knitr)
library(rvest)
library(gsubfn)
library(shiny)
library(ggplot2)
library(dplyr)
library(plotrix)
library(plotly)
library(tidyr)
library(tmap)
library(rmarkdown)
library(DT)
library(rgdal)
library(rgeos)
library(digest)
library(readr)
library(rvest)
library(dplyr)
library(gsubfn)
library(ggplot2)
library(mosaic)
library(maptools)
library(extrafont)
library(rworldmap)

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
